baseURL = 'https://ryongyong.github.io'
languageCode = 'ja'
title = "ryongyong Dialy"
theme = "hugo_theme_robust"


disqusShortname = "XYW"

[params]
description = "This is site description"
dateformat = "Jan 2, 2006" # Optional
# Fonts settings.
googlefonts = "https://fonts.googleapis.com/css?family=Lobster|Lato:400,700" # Optional, Include google fonts.
fontfamily = "Lato,YuGothic,'Hiragino Kaku Gothic Pro',Meiryo,sans-serif" # Optional, Override body font family.
logofontfamily = "Lobster, cursive" # Optional, Override logo font.

enableHighlight = true # highlight.js option

[params.author]
thumbnail = "images/author.jpg"
name = "ryongyong"
description = "<p>Software Engineer</p><p></p>"
twitter = "https://twitter.com/ryongyong"
github = "https://github.com/ryongyong"

[outputs]
page = [ "HTML", "AMP" ] # if you want AMP enable.