baseURL = 'https://ryongyong.github.io'
languageCode = 'ja'
title = 'Ryongyong'
theme = "hugo_theme_robust"


disqusShortname = "XYW"

[params]
description = "This is site description"
dateformat = "Jan 2, 2006" # Optional
# Fonts settings.
googlefonts = "https://fonts.googleapis.com/css?family=Lobster|Lato:400,700" # Optional, Include google fonts.
fontfamily = "Lato,YuGothic,'Hiragino Kaku Gothic Pro',Meiryo,sans-serif" # Optional, Override body font family.
logofontfamily = "Lobster, cursive" # Optional, Override logo font.

enableHighlight = true # highlight.js option

[params.author]
thumbnail = "images/author.jpg"
name = "John Doe"
description = "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit</p><p>sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>"
facebook = "https://www.facebook.com/daisuke.tsuji.735"
twitter = "https://twitter.com/dim0627"
github = "https://github.com/dim0627"

[outputs]
page = [ "HTML", "AMP" ] # if you want AMP enable.