baseURL = 'https://ryongyong.github.io/'
languageCode = 'ja'
defaultContentLanguage = "ja"
hasCJKLanguage = true
title = "パンダ好き"
theme = "hugo_theme_robust"
mainSections = ["posts"]

disqusShortname = "XYW"

[params]
description = "パンダ好きエンジニアの日記的なもの"
dateformat = "Jan 2, 2006" # Optional
# Fonts settings.
googlefonts = "https://fonts.googleapis.com/css?family=Lobster|Lato:400,700" # Optional, Include google fonts.
fontfamily = "Lato,YuGothic,'Hiragino Kaku Gothic Pro',Meiryo,sans-serif" # Optional, Override body font family.
logofontfamily = "Lobster, cursive" # Optional, Override logo font.

enableHighlight = true # highlight.js option

[params.author]
thumbnail = "images/author.jpg"
name = "ryongyong"
description = "<p>パンダが好きなSoftware Engineer. 物理生まれ物理育ち.</p><p></p>"
twitter = "https://twitter.com/ryon_yon_che"
github = "https://github.com/ryongyong"

[outputs]
page = [ "HTML", "AMP" ] # if you want AMP enable.